# ────────────────────────────────────────────────────────────
# Omarchy Matte Black Theme for Alacritty
# By tahayvr
# https://github.com/tahayvr
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 12
padding.y = 12

[font]
size = 12.0



[colors]
[colors.primary]
background = "#121212"
foreground = "#bebebe"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#333333"
red = "#D35F5F"
green = "#4D8E4F"
yellow = "#b91c1c"
blue = "#4F4D8F"
magenta = "#D35F5F"
cyan = "#bebebe"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#B91C1C"
green = "#4D8E4F"
yellow = "#b90a0a"
blue = "#4F4D8F"
magenta = "#B91C1C"
cyan = "#eaeaea"
white = "#ffffff"
