accent = "#e68e0d"
active_border_color = "#8A8A8A"
active_tab_background = "#121212"

cursor = "#eaeaea"
foreground = "#bebebe"
background = "#121212"
selection_foreground = "#bebebe"
selection_background = "#333333"

color0 = "#333333"
color1 = "#D35F5F"
color2 = "#4D8E4F"
color3 = "#F3C70D"
color4 = "#4F4D8F"
color5 = "#5F5FD3"
color6 = "#5FD3D3"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#B91C1C"
color10 = "#FFC107"
color11 = "#b90a0a"
color12 = "#f59e0b"
color13 = "#B91C1C"
color14 = "#eaeaea"
color15 = "#ffffff"
